### ISSUE TITLE
New Error (Please Help Me Fix It)

### ISSUE THREAD

**Issue by J35t3rOP** [masokky/instagram-tools#36]
(node:5145) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:5145) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Error: error logging attribution
    at /home/kali/instafollow/node_modules/instagram-private-api/dist/core/session.js:156:19
    at tryCatcher (/home/kali/instafollow/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kali/instafollow/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/kali/instafollow/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/kali/instafollow/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/kali/instafollow/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/kali/instafollow/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/kali/instafollow/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/kali/instafollow/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/kali/instafollow/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by krishealty** [comment]
It seems like you are using this tool in kali linux, or you are using an old termux, that's why it can't read the python file
